"""
Grounded reply drafting.

Approach: BM25 retrieval over historical (customer_text -> brand_text)
pairs, filtered to the predicted intent bucket, to find the K most
similar previously-resolved cases. The draft is then generated by an
LLM call *grounded in those retrieved resolutions* (few-shot, retrieval-
augmented), so the agent isn't inventing a policy — it's reusing how
this brand actually handled similar issues before.

LLM WIRING: this calls the Anthropic API if ANTHROPIC_API_KEY is set in
the environment. If it isn't (e.g. running this eval harness in a
sandbox with no key), we fall back to an extractive draft: the
single best-matching historical resolution, lightly re-personalized.
This fallback is intentionally simple and is graded as a *baseline*,
not hidden as if it were the real system — see eval/evaluate_replies.py
where both paths are scored separately.
"""
import os
import re
from rank_bm25 import BM25Okapi
from src.ingest import load_brand_pairs

_TOKEN_RE = re.compile(r"[a-z0-9]+")


def tokenize(text: str):
    return _TOKEN_RE.findall(text.lower())


class GroundedRetriever:
    def __init__(self, pairs_df, intent_lookup=None):
        """pairs_df: DataFrame with customer_text, brand_text columns.
        intent_lookup: optional dict tweet_id -> intent, to allow filtering
        retrieval to the same intent bucket (reduces off-topic grounding).
        """
        self.pairs = pairs_df.reset_index(drop=True)
        self.corpus_tokens = [tokenize(t) for t in self.pairs["customer_text"]]
        self.bm25 = BM25Okapi(self.corpus_tokens)

    def retrieve(self, query_text, k=3):
        scores = self.bm25.get_scores(tokenize(query_text))
        top_idx = scores.argsort()[::-1][:k]
        results = []
        for i in top_idx:
            results.append({
                "customer_text": self.pairs.iloc[i]["customer_text"],
                "brand_text": self.pairs.iloc[i]["brand_text"],
                "score": float(scores[i]),
            })
        return results


def draft_with_llm(customer_text, retrieved, brand="AppleSupport"):
    """Real grounded generation path. Requires ANTHROPIC_API_KEY."""
    import anthropic
    client = anthropic.Anthropic()

    context = "\n\n".join(
        f"Past similar customer message: {r['customer_text']}\n"
        f"How {brand} resolved it: {r['brand_text']}"
        for r in retrieved
    )
    prompt = f"""You are drafting a reply as {brand}'s Twitter support account.
Use the past resolutions below as your ONLY source of policy/process —
do not invent steps, links, or commitments that aren't grounded in them.
If the past cases don't cover something, say you'll look into it rather
than guessing.

{context}

New customer message: {customer_text}

Draft a reply in {brand}'s voice: helpful, concise, no more than 3-4
sentences, matching the tone of the past resolutions."""

    resp = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=300,
        messages=[{"role": "user", "content": prompt}],
    )
    return resp.content[0].text.strip()


def draft_extractive_fallback(customer_text, retrieved):
    """No-API-key fallback: reuse the top retrieved resolution, with a
    short personalized opener. This is the SIMPLE BASELINE for reply
    quality, not the target system — see report.md."""
    if not retrieved:
        return "Thanks for reaching out — we're looking into this and will follow up shortly."
    best = retrieved[0]["brand_text"]
    return best


def draft_reply(customer_text, retriever: GroundedRetriever, k=3, use_llm=None):
    retrieved = retriever.retrieve(customer_text, k=k)
    use_llm = (os.environ.get("ANTHROPIC_API_KEY") is not None) if use_llm is None else use_llm
    if use_llm:
        try:
            draft = draft_with_llm(customer_text, retrieved)
            method = "llm_grounded"
        except Exception as e:
            draft = draft_extractive_fallback(customer_text, retrieved)
            method = f"extractive_fallback (llm_error: {e})"
    else:
        draft = draft_extractive_fallback(customer_text, retrieved)
        method = "extractive_fallback (no ANTHROPIC_API_KEY set)"
    return {
        "draft": draft,
        "method": method,
        "grounding": retrieved,
    }


if __name__ == "__main__":
    pairs = load_brand_pairs("data/sample_twcs.csv", "AppleSupport")
    retriever = GroundedRetriever(pairs)
    test_msg = "my iphone battery is draining so fast since the last update, please help"
    result = draft_reply(test_msg, retriever)
    print("METHOD:", result["method"])
    print("DRAFT:", result["draft"])
    print("\nGROUNDED ON:")
    for g in result["grounding"]:
        print(f"  [{g['score']:.2f}] {g['customer_text'][:70]}")
